"$schema" = 'https://starship.rs/config-schema.json'

format = """
[ ](fg:color_aqua)\
$directory\
[](fg:color_aqua)\
$git_branch\
$fill\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_bg1 bg:color_bg3)\
$time\
$cmd_duration\
[ ](fg:color_bg1)\
$line_break$character"""

# add_newline = false
palette = 'everforest'
# command_timeout = 10

[palettes.everforest]
color_fg0 = '#d3c6aa'
color_bg1 = '#272e33'
color_bg3 = '#2e383c'
color_blue = '#7fbbb3'
color_aqua = '#83c092'
color_green = '#a7c080'
color_orange = '#e69875'
color_purple = '#d699b6'
color_red = '#e67e80'
color_yellow = '#dbbc7f'
color_gray0 = '#7A8478'
color_gray1 = '#859289'
color_gray2 = '#9DA9A0'

[fill]
symbol = "·"
style = "bold color_gray0"

[cmd_duration]
min_time = 500
format = '[[ $duration ](fg:color_aqua bg:color_bg3)]($style)'

[os]
format = "[ $symbol ]($style)"
disabled = false
style = "bg:color_aqua fg:color_bg1"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:color_orange fg:color_bg1"
style_root = "bg:color_orange fg:color_bg1"
format = '[ $user ]($style)'

[directory]
style = "fg:color_bg1 bg:color_aqua"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_orange"
format = '[[ $symbol $branch ](fg:color_orange)]($style)'

[git_status]
style = "bg:color_orange"
format = '[[($all_status$ahead_behind )](fg:color_orange)]($style)'

[nodejs]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_blue)]($style)'

[c]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_blue)]($style)'

[rust]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_blue)]($style)'

[golang]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_blue)]($style)'

[php]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_blue)]($style)'

[java]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_blue)]($style)'

[kotlin]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_blue)]($style)'

[haskell]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_blue)]($style)'

[python]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_blue)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:#83a598)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_fg0 bg:color_bg1)]($style)'

[line_break]
disabled = false

[character]
disabled = false

success_symbol = '[ ](bold fg:color_aqua)'
error_symbol = '[ >](bold fg:color_red)'
vimcmd_symbol = '[ >](bold fg:color_green)'
vimcmd_replace_one_symbol = '[ <](bold fg:color_purple)'
vimcmd_replace_symbol = '[ <](bold fg:color_purple)'
vimcmd_visual_symbol = '[ <](bold fg:color_yellow)'
